apiVersion: batch/v1
kind: CronJob
metadata:
  name: cost-tracker-cronjob
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          serviceAccountName: cost-tracker-sa
          containers:
          - name: cost-tracker
            image: ghcr.io/jayzsec/cost-tracker:latest
            envFrom:
            - configMapRef:
                name: cost-tracker-config
            - secretRef:
                name: cost-tracker-secret
          restartPolicy: OnFailure