---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cost-tracker-secret
  namespace: default
spec:
  encryptedData:
    COSTTRACKER_SLACK_WEBHOOK_URL: AgBZmhn+vbsOw4N4rY7OsP4h9sVrC+87OvH4SSUD/u5ANqKPqoAliQBHUEqFmV07RN3VGqf382+2XcyanlLm+ZBZLiR5xCxEDpAW/D5vroA2itH5UxTAdw7nOzrwPE3++7+LV0cNCLCzqpp7PFCpZtFzWePG37NZ0lAOipWzHb1k/7n8nB4Zd+sa6KMss1pR2ZplUMTsIFgnc67aaNm9S1xOBfQngdKtanRT1sRvMIC+4Ih8+LpC5mZuQBiynu3tA4eFQh7R4pwxi8+PZpQ6TRiN//3N0X0Ks+OE3WnABiKtruzr2MqeYL1dh7QXdmIC5lIqK+jDrcl0M3NJ+MRdzPQ5ayzxYdLuXFJkvUykUiorNq2Tw0tT0GqScQGw7Wx/KT+VbdMJDzLr+YuqHC2ngNf6X/LdY7gXrG7IcusxYywYmHPzh/8fSkn0oeyz8+QNk6qRguBJ9+pCvqvwZ3VoOzD9nvT2aKIZ1Uws9BIyqhVgD5Y4Z9JOVkLU7sKS3e0onUPDH8hmfFqj/Bp6a1t9jsLhSzTUjEHLzDG0SwE3JLYs28NujDhvOD62If0eCOCZa6auxgDEI2EjkhTomCaxyDh1sZY0B7flOC/7TOxVb6gti/UflUCgwq8R7QH/7cmhXmQDwHQmPDBNKsRhO0aaO5Uar5MAdKx3UB8spIwV8g5gKUKqD1C53l3Xm14iCk+EVGJ/qyTzD8cnzkCW6uy7lzl9nPWQhnUZakM0i3kwm35Q3c3VFFvMyzGir9fc4oCRkUjfHJYw5xASA/xv0XnP2gyWEuwwY3mbBKgk5n6/9fumzok=
  template:
    metadata:
      creationTimestamp: null
      name: cost-tracker-secret
      namespace: default
    type: Opaque
