---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cost-tracker-secret
  namespace: default
spec:
  encryptedData:
    COSTTRACKER_SLACK_WEBHOOK_URL: AgCFG/eg15PK1ANNpqhs57FANUsWGUb1UrNyjwxck8pVloSpJUxlCfdDfYcMllbYD4N4x2r6KIaxjwEValTJcqSaqSirVl8Ih9qoa5ubskA/x8pvibbXFjJWgK7y5TdOjgS08EhOVHLuuoOBPeBS/ysQF7Zly73AdPqPf1h+lneuB6QWrCwVKeE5049xNDLfO5guAcotM13/WXG4R6mFXign0js/92cwtYUGXrmW9t9HwG6R37FJ86Gy5y9zmswOg5dJaJuZZ6fx8IYZnhUYy9fu7SvuRQQlL9iejQm4jLJzWiouQL2d/CxNqJ43GLpl4PXi/php3mN6EOLjY+iFC7F+kidYJVzh23HBn22rnrZBVHX9a9ztBzpypTh3zG9lYczqCVJCt3i0U5zYq/Yf6zFvdI/LZ+8qTN40weHtQtlR/WcI6rQgl2aZL3pZRh0jG4/YmQf6BwHdFDgrSrrjIpzxbsnjE3qXGCTJf9YIOaJ92TMINlrJ0nwIGRs0tGYT3Qy7ByusWIWMmBmadie3bE7lUtqYX6/VRXlmPnFl6shhTcFY3KrxHeo/cBOD92+Xs6uoUBgOlswo075pcLdyxyxl9lS/RSlyC6c26iHqvi1uL7hGvk0Cby2neH0YK/5h7GWqw6vuKGwnH71kSLzzMyfjUclwtnAgQpTVUbsMUwKIDFr34vG3pWxEpX4gYsk9tBtV0hiMpsed4OuUCTLH3NpWxqazSGQOtig5Z31e6n8ev8JUZ8jJxdnoVmVerLC2bt3UqT7HQJnJvwG7USyTdSMBFQdEe8MWlhSXhw9LvBGOGCE=
  template:
    metadata:
      creationTimestamp: null
      name: cost-tracker-secret
      namespace: default
    type: Opaque
