# kubernetes/secret.template.yaml (Corrected with stringData)
apiVersion: v1
kind: Secret
metadata:
  name: cost-tracker-secret
type: Opaque
# Use 'stringData' to provide the secret as a plain string.
# Kubernetes will handle the base64 encoding automatically.
stringData:
  # The key is the environment variable Viper expects
  COSTTRACKER_SLACK_WEBHOOK_URL: "<YOUR_REAL_SLACK_WEBHOOK_URL_HERE>"